language: python

dist: bionic

# https://devguide.python.org/#branchstatus
python:
  - 3.6
  - 3.7

install:
  - pip install -r requirements.txt
  - pip install flake8 sphinx sphinx-rtd-theme
script:
  - flake8 s5a
  - make -C docs clean html
